<?php
global $data;

$data = array(
    'speakers' => array(
        '1' => array(
            'name' => 'Cal Evans',
            'image' => 'images/speakers/cal.evans.jpg',
            'company' => 'Blue Parabola',
            'twitter' => 'calevans',
            'website' => 'http://blog.calevans.com/',
            'description' => 'For the past 13 years Cal has worked with PHP and MySQL on Linux, OSX, and Windows. He has built a variety of projects ranging in size from simple web pages to multi-million dollar web applications. When not banging his head on his monitor, attempting a blood sacrifice to get a particular piece of code working, he enjoys building and managing development teams using his widely imitated but never patented management style of "management by wandering around". These days, when not working with PHP, Cal can be found working on a variety of projects, most of which require a higher security clearance than you have so they can’t be listed here.',
            'talks' => array(1),
        ),
        '2' => array(
            'name' => 'Paul Jones',
            'image' => 'images/speakers/paul.jones.jpg',
            'company' => 'Parchment',
            'twitter' => 'pmjones',
            'website' => 'http://paul-m-jones.com/',
            'description' => 'Paul is an internationally recognized PHP expert who has worked as everything from junior developer to VP of Engineering in all kinds of organizations (corporate, military, non-profit, educational, medical, and others).    Paul\'s latest open-source project is the Aura project for PHP. Among his other accomplishments, Paul is the lead developer of the Solar Framework, and the creator of the Savant template system. He has authored a series of authoritative benchmarks on dynamic framework performance, and was a founding contributor to the Zend Framework (the DB, DB_Table, and View components). In a previous career, Paul was an intelligence operations specialist for the US Air Force, and enjoys putting .308 holes in targets at 400 yards.',
            'talks' => array(11),
        ),
        '3' => array(
            'name' => 'Chris Hartjes',
            'image' => 'images/speakers/chris.hartjes.jpg',
            'company' => '',
            'twitter' => 'grmpyprogrammer',
            'website' => 'http://www.littlehart.net/',
            'description' => 'Chris has been building web applications of all shapes and sizes since 1998, ranging from searchable CD catalogs for professional DJ\'s to large-scale dating web sites. A huge consumer of open-source software, he tries to give back to the community via Twitter, his blog, speaking at conferences, and by co-organizing the Greater Toronto Area PHP User Group. He is also a big believer in the power of best practices, commitment to testing, and automation as secret weapons for organizations to deliver high quality applications quickly. Chris has also self-published two books about refactoring and testing PHP applications. He works from his home office in Milton, Ontario, Canada where he lives with his long-suffering wife, two daughters and two cats.',
            'talks' => array(2,23),
        ),
        '4' => array(
            'name' => 'Logan Reese',
            'image' => 'images/speakers/logan.reese.jpg',
            'company' => 'SoftLayer',
            'twitter' => null,
            'website' => null,
            'description' => 'Logan Reese serves as Senior Systems Architect for SoftLayer. In this role, he is responsible for architectural oversight of systems being developed on SoftLayer’s Platform. As an accomplished technology connoisseur, he previously served Systems Architect leading the design integration plans for the merger of SoftLayer and The Planet. Previously Logan served as a Software Engineer at SoftLayer. Responsible for the design and construction of SoftLayer’s Platform that powers SoftLayer’s internal systems and API. Prior to his tenure with SoftLayer, he was Senior Software Engineer, leading the automated provisioning systems at The Planet. He also served as NOC engineer for The Planet; responsible for building and provisioning ServerMatrix dedicated servers and providing support.',
            'talks' => array(24),
        ),
        '5' => array(
            'name' => 'Ben Lake',
            'image' => 'images/speakers/ben.lake.jpg',
            'company' => 'SoftLayer',
            'twitter' => null,
            'website' => null,
            'description' => 'Ben Lake has spent a decade working with PHP on projects including work flow management for a copy center, e-commerce sites with integrated end-to-end order fulfillment, and most recently automated infrastructure management. He has a habit of tackling problems that are not necessarily fun, hip, or neat. He recognizes the value of software is derived from its life, not its birth. Maintenance is key, the necessity of re-factoring should be recognized from the beginning of any software endeavor. Despite this he still enjoys software development and looks forward to ever changing requirements demanded by industry. In order to let of steam that most definitely accumulates during the challenges of continuous change, he enjoys rock climbing, gardening, and caring for his chickens.',
            'talks' => array(24),
        ),
        '6' => array(
            'name' => 'Derick Rethans',
            'image' => 'images/speakers/derick.rethans.jpg',
            'company' => '10gen',
            'twitter' => 'derickr',
            'website' => 'http://derickrethans.nl/',
            'description' => 'Derick Rethans is a PHP internals expert, author of Xdebug and an OpenStreetMap and mapping enthusiast. He has contributed in a number of ways to the PHP project, including the Xdebug debugging tool, and various extensions and additions. He\'s a frequent lecturer at conferences, the author of php|architect\'s Guide to Date and Time Programming, and the co-author of PHP 5 Power Programming. He\'s now working with 10gen to help improve the MongoDB PHP driver. In his spare time, he contributes to the OpenStreetMap project. He also likes to travel, hike, ski and practice photography.',
            'talks' => array(5,20),
        ),
        '7' => array(
            'name' => 'Bob Majdak',
            'image' => 'images/speakers/bob.majdak.jpg',
            'company' => 'Ardent, Inc.',
            'twitter' => 'bobmajdakjr',
            'website' => 'http://catch404.net/',
            'description' => 'Bob Majdak is a web developer who has been using PHP as a core development tool since 1999. He started working on the web back then joining the PlanetQuake gamer site, and in the early 2000s he was a part of the KateOS Linux core team - which became the first distro to implement system administration tools with PHP-GTK. Now he works on framework development focusing on both the web and server side of managing an application. He enjoys finding new places to stick PHP, especially when someone tells him not to.',
            'talks' => array(6),
        ),
        '8' => array(
            'name' => 'Elizabeth Smith',
            'image' => 'images/speakers/elizabeth.smith.jpg',
            'company' => 'MojoLive',
            'twitter' => 'auroraeosrose',
            'website' => 'http://emsmith.net/',
            'description' => 'Elizabeth M. Smith is a developer, speaker, and writer with an unhealthy obsession with learning new programming languages and making everything compile on windows. She enjoys doing very perverse things to Windows using PHP as well - all this in between caring for her 4 kids, husband, golden retriever, and cat who thinks she\'s a dog. She has currently jumped into the wild world of startups with a job at MojoLive where she\'s going to attempt to create something useful.',
            'talks' => array(4,13),
        ),
        '9' => array(
            'name' => 'Joël Perras',
            'image' => 'images/speakers/joel.perras.jpg',
            'company' => 'Fictive Kin',
            'twitter' => 'jperras',
            'website' => 'http://nerderati.com/',
            'description' => 'I\'m an ex-physicist turned Big Data geek. Life is weird like that. My days are spent building awesome stuff with the rest of the fine folk at Fictive Kin, contributing to open source projects that help make the life of a developer just a bit easier, and trying to lift large weights over my head on a regular basis. I specialize in creating application and data architectures for web startups, and love every minute of it.',
            'talks' => array(7,21),
        ),
        '10' => array(
            'name' => 'Jeff Carouth',
            'image' => 'images/speakers/jeff.carouth.jpg',
            'company' => 'Liftopia',
            'twitter' => 'jcarouth',
            'website' => 'http://carouth.com/',
            'description' => 'Jeff Carouth works on the Internet. He’s been a very passionate web developer since 2003 and works tirelessly as a member of Team Dev at Liftopia. When he’s not working you’ll likely find him at a community event. He owes a huge debt to the tech community surrounding technologies he uses on a daily basis, so he tries to give back as much as possible. He is a co-organizer of the BCS PHP User Group in Bryan/College Station, Texas, a frequent participant in WebGeekHappyHour, a conference speaker, and one of the team that brought HTML5.tx to life in 2011. Follow Jeff as "jcarouth" on Twitter and Github.',
            'talks' => array(18),
        ),
        '11' => array(
            'name' => 'Davey Shafik',
            'image' => 'images/speakers/davey.shafik.jpg',
            'company' => 'Engine Yard',
            'twitter' => 'dshafik',
            'website' => 'http://daveyshafik.com/',
            'description' => 'Davey Shafik has been working with PHP and the LAMP stack, as well as HTML, CSS, and JavaScript for over a decade. With numerous books, articles, and conference appearances under his belt, he enjoys teaching others any way he can. An avid photographer, he lives in sunny Florida with his wife and 6 cats.',
            'talks' => array(3,16),
        ),
        '12' => array(
            'name' => 'Keith Casey',
            'image' => 'images/speakers/keith.casey.jpg',
            'company' => 'Twilio',
            'twitter' => 'caseysoftware',
            'website' => 'http://caseysoftware.com/',
            'description' => 'Keith Casey has been a developer for over a decade and helps organize various tech communities. Previously, he was a professional agitator within the Washington, DC until he decided to explore Austin, TX in 2010. To pay the bills, he works as a Developer Evangelist for Twilio to get good tools to good developers so they can build great things. Previously, he built large-scale PHP-based systems for organizations ranging from major news companies to small non-profits. In his spare time, he is a core contributor to web2project, works to build and support the Austin PHP community, co-founded the HubAustin coworking space in South Austin, blogs regularly at CaseySoftware.com and is completely fascinated by monkeys.',
            'talks' => array(22),
        ),
        '13' => array(
            'name' => 'Vance Lucas',
            'image' => 'images/speakers/vance.lucas.jpg',
            'company' => 'Brightbit',
            'twitter' => 'vlucas',
            'website' => 'http://www.vancelucas.com/',
            'description' => 'Vance Lucas is a seasoned programmer with over 12 years of PHP experience dating back to when PHP3 was first released. He is the founder and president of the Oklahoma City JavaScript User group, and helps to grow and foster the local web development community. Vance created and maintains the Alloy HMVC Framework, Stackbox CMS, phpDataMapper, and Frisby.js open-source projects. He is the co-founder of Brightbit, and enjoys working on new startup and business ideas, web projects, and mobile apps.',
            'talks' => array(14),
        ),
        '14' => array(
            'name' => 'Chris Weldon',
            'image' => 'images/speakers/chris.weldon.jpg',
            'company' => 'Improving Enterprises',
            'twitter' => 'neraath',
            'website' => 'http://www.chrisweldon.net/',
            'description' => 'Chris Weldon has been developing agile-centric solutions in PHP since 2003. Chris has been reading, loving, living, and mentoring PHP developers and teams to build high quality, high value solutions. Chris\' bailiwick includes implementing identity management solutions for a wide range of applications, including web service infrastructure and Zend Framework-based web applications. Sharing his knowledge by speaking at user groups, universities, conferences, and one-on-one with others is a passion. Chris has been a speaker for several Aggieland and corporate user groups, tech fests, and other conferences and technology groups alike. Chris is also the co-organizer of the B/CS PHP Users Group, blogs at http://www.chrisweldon.net, and is an occasional contributor to Improving Podcasts.',
            'talks' => array(12),
        ),
        '15' => array(
            'name' => 'Shaun Farrell',
            'image' => 'images/speakers/shaun.farrell.jpg',
            'company' => null,
            'twitter' => 'farrelley',
            'website' => 'http://www.farrelley.com/',
            'description' => 'Shaun Farrell has been developing PHP for the past 7 years and is the Co-Founder of PintLabs L.L.C. He recently moved to Raleigh, NC to be closer to the PintLabs team. Shaun has been using ElasticSearch (ES) for the past year and recently has redeveloped the BreweryDB.com and BreweryDB API search using ES. #lovesbeer',
            'talks' => array(8),
        ),
        '16' => array(
            'name' => 'Jeff Winesett',
            'image' => 'images/speakers/jeff.winesett.jpg',
            'company' => 'TextureMedia',
            'twitter' => 'seesawlabs',
            'website' => 'http://www.seesawlabs.com/',
            'description' => 'Jeff Winesett is VP of Technology at TextureMedia, Inc. in Austin Tx. He has many years experience in Web application development working with both start-ups and fortune 500 companies. He has been helping facilitate companies in their transition to cloud-based infrastructure since 2009. He has several publications on PHP and PHP-based frameworks, including Agile Web Application Development with Yii 1.1 and PHP5.',
            'talks' => array(10),
        ),
        '17' => array(
            'name' => 'Omni Adams',
            'image' => 'images/speakers/omni.adams.jpg',
            'company' => 'Glam',
            'twitter' => 'omnicolor',
            'website' => 'http://omni-spot.blogspot.com/',
            'description' => 'Omni Adams is a professional web developer currently plying his trade for Glam Media (formerly Ning). When not playing hockey he likes to work on improving build systems so that he doesn\'t ever have to do manual processes again and believes that anything you have to do more than once is worth completely automating.',
            'talks' => array(15),
        ),
        '18' => array(
            'name' => 'Geoffrey Tran',
            'image' => 'images/speakers/geoffrey.tran.jpg',
            'company' => 'RAPP',
            'twitter' => 'geoffreytran',
            'website' => 'http://geoffreytran.com/',
            'description' => 'Geoff is a creative technologist that focuses on creating innovative experiences. At RAPP, he has worked on projects for clients such as The Bahamas, AMC Theatres, AMD, 7-Eleven and Bank of America. At Moverati, an automated video startup, he architected and developed the infrastructure to process over 500,000 user generated pictures and videos monthly for the NFL Experience and Under Armour. At JWT, Geoff worked on projects for the US Marine Corps that ranged from SEO to 508 compliance on Marines.com and other digital properties. Geoff is also a contributor to open source projects such as Zend Framework and Symfony.',
            'talks' => array(9),
        ),
        '19' => array(
            'name' => 'John Syrinek',
            'image' => 'images/speakers/john.syrinek.jpg',
            'company' => 'Splash Cube',
            'twitter' => 'johntron',
            'website' => 'http://johntron.com',
            'description' => 'John\'s been writing code since the 5th grade. After bailing out of college, he built ReviewAnalyst, a social media management tool for the hospitality industry. He then returned to school to complete his degree. While at UT Dallas, John built a social mapping platform called Placethings, which he presented at SXSWi BizSpark Accelerator in 2008. He\'s currently working at SplashMedia. His latest project, SplashCube, is an all-in-one social media recommendation, management, and analytics platform. John will be giving you a rundown of SplashCube\'s infrastructure and share what he\'s learned building crawlers the hard way.',
            'talks' => array(17),
        ),
        '20' => array(
            'name' => 'Garrett Woodworth',
            'image' => 'images/speakers/garrett.woodworth.jpg',
            'company' => 'Engine Yard',
            'twitter' => 'gwoo',
            'website' => 'http://www.ohloh.net/accounts/gwoo',
            'description' => 'Garrett Woodworth, better known as GWoo, is a passionate open source developer and community member. He earned street cred as project manager of CakePHP, where he focused on usability and development. Gwoo continues to innovate in PHP web framework space as project manager of Lithium, the most rad PHP framework. He values test-driven development and looks to promote better quality open source software through process and tooling. He likes Git, MongoDb, ZeroMQ, and Clouds. When not working on open source projects, Gwoo is currently engineering distributed systems at EngineYard, Inc. Gwoo holds a bachelor\'s degree in history from the University of Hawaii and a JD/MBA from Fordham University, where he studied intellectual property and information systems.',
            'talks' => array(19),
        ),
    ),
    'talks' => array(
        '1' => array(
            'title' => '!Normal===Awesome!',
            'presenter' => 'Cal Evans',
            'description' => 'As PHP developers we are about as far from normal as you can get. Traditional developers master their craft, charge when they work and go home on the weekends and putter around in their workshops. Many PHP developers give away what they know, help others freely and spend their weekends coding to talking about coding. The cool thing is, the thing that makes us not normal is the thing that makes us so awesome. Lets celebrate our lack of normality and revel our awesomeness. Fly your freak flag proudly; you are a PHP developer and you build the web!',
            'room' => 'Sycamore',
            'joindin' => 'http://joind.in/6334',
            'date' => '2012-06-29',
            'time' => '0920',
        ),
        '2' => array(
            'title' => 'Building Testable PHP Applications',
            'presenter' => 'Chris Hartjes',
            'description' => 'There is lots of info out there on how to use testing tools but very little info on how to build your application in such a way that it can easily be tested. This talk will cover strategies that can be used to shape your application in such a way that you\'ll be making production pushes multiple times a day with complete confidence.',
            'room' => 'Sycamore',
            'joindin' => 'http://joind.in/6335',
            'date' => '2012-06-29',
            'time' => '1030',
        ),
        '24' => array(
            'title' => 'Coordinating Workflows Across Machine Boundaries',
            'presenter' => 'Ben Lake & Logan Reese',
            'description' => 'There is a lot of talk about scaling, but not nearly as much about what to do when you\'ve scaled. This presentation will delve into techniques for coordinating workloads across physical machine boundaries. The focus will be on how to harness the power of Zookeeper and nifty ways to abstract algorithms used to handle contention for shared resources.',
            'room' => 'Acacia',
            'joindin' => 'https://joind.in/6701',
            'date' => '2012-06-29',
            'time' => '1030',
        ),
        '3' => array(
            'title' => 'PHP 5.4: The New Bits',
            'presenter' => 'Davey Shafik',
            'description' => 'PHP 5.4 is about to be unleashed into the world; bringing some of the most exciting changes to the PHP language to date. This talks covers everything you need to know to get up to speed!',
            'room' => 'Sycamore',
            'joindin' => 'http://joind.in/6336',
            'date' => '2012-06-29',
            'time' => '1130',
        ),
        '4' => array(
            'title' => 'PHP Extensions for Dummies',
            'presenter' => 'Elizabeth Smith',
            'description' => 'Ever had a need for some library in C in your PHP code? Or want to hook into the engine to do evil? Or maybe you just want to make some part of PHP better. And then you say "but I don\'t know enough C". PHP extensions are actually quite easy to write, even for those with only the smallest amount of C knowledge, if you know the secret incantations. Write your own extension in this step by step tutorial which assumes you know nothing of PHP internals, the very basics of C syntax and little more, and have the ability to type "./configure && make && make install && make test"',
            'room' => 'Acacia',
            'joindin' => 'http://joind.in/6337',
            'date' => '2012-06-29',
            'time' => '1130',
        ),
        '5' => array(
            'title' => 'OpenStreetMap and PHP',
            'presenter' => 'Derick Rethans',
            'description' => 'This presentation introduces OpenStreetMap and explains to the audience what sort of rich data set it has and how to use it from PHP (and JavaScript). I will also cover different APIs for using the map tiles as well as other APIs that form sister-projects to OSM, such as Nominatim (search), routing, and obtaining current-location information.  For the data storage and querying aspects we will be looking at MongoDB. During the course of the presentation I will also have to dip into some of the theoretical issues surrounding map making in general.',
            'room' => 'Sycamore',
            'joindin' => 'http://joind.in/6338',
            'date' => '2012-06-29',
            'time' => '1345',
        ),
        '6' => array(
            'title' => 'Pixel Punching with PHP',
            'presenter' => 'Bob Majdak Jr.',
            'description' => 'Pulling your hair out because that one user keeps uploading a 10megapixel raw image as his avatar? Customers want to upload images that have to be stylized so they don\'t make your site look like it walked out of a Geocities neighborhood? Come learn about the ins and outs of server-side image manipulation in PHP. Compare and contrast the two major libraries, Imagick and GD, their performance quirks, and learn how to produce those cool retro photos on the Hipstergrams!',
            'room' => 'Acacia',
            'joindin' => 'http://joind.in/6339',
            'date' => '2012-06-29',
            'time' => '1345',
        ),
        '7' => array(
            'title' => 'A Soft Introduction to Machine Learning',
            'presenter' => 'Joël Perras',
            'description' => 'To many, "Machine learning" seems like a magical black box that somehow tells us what books we\'re interested in buying on Amazon, what movies we\'d like to watch on Netflix, or what coffee shops we\'d like to visit on Foursquare. In this 50 minute session, we\'ll attempt to demystify some of the ML techniques that are employed in building a recommendation engine for a product catalog, discuss some of the capabilities and limitations of recommender systems, storage and querying solutions for millions of rows and millions of columns, all while avoiding the inevitable rise of SkyNet.',
            'room' => 'Sycamore',
            'joindin' => 'http://joind.in/6340',
            'date' => '2012-06-29',
            'time' => '1445',
        ),
        '8' => array(
            'title' => 'ElasticSearch for PHP',
            'presenter' => 'Shaun Farrell',
            'description' => 'Most of the time search is the last thing you think of. Then it is almost release time and it dawns on you that you have no search. The first thing you think of is MySQL full-text search. You mention it to the boss and tell him its the easiest solution to get out the door the quickest. He agrees, you do it, then realize your search SUCKS! Let me introduce you to ElasticSearch! A simple fast, schema free, multi-tenancy, lucene based search engine. Lets explore everything from simple setup, to doing queries and finish off with some advanced document searching. ElasticSearch is so easy and cool. It\'s bonsai cool!',
            'room' => 'Acacia',
            'joindin' => 'http://joind.in/6341',
            'date' => '2012-06-29',
            'time' => '1445',
        ),
        '9' => array(
            'title' => 'Stop Exposing Yourself: Exploits, Attacks and Defenses',
            'presenter' => 'Geoffrey Tran',
            'description' => 'A talk about security issues and exploits in the web with a focus on PHP. We will cover common exploits and how to defense yourself from them.',
            'room' => 'Sycamore',
            'joindin' => 'http://joind.in/6342',
            'date' => '2012-06-29',
            'time' => '1545',
        ),
        '10' => array(
            'title' => 'Migrating to the Cloud - Actually taking flight',
            'presenter' => 'Jeff Winesett',
            'description' => 'While Cloud talks may be "soooo last year", many have not yet had the opportunity to really get started using cloud-based infrastructure. In this tutorial, you\'ll be introduced to many of the offerings within Amazon\'s Web service suite, and actually learn how to take advantage of them. We\'ll get our hands dirty setting up LAMP stack instances, mounting Elastic Block Storage, configuring security groups, associating Elastic IPs, configuring a load balancer, using S3 as file storage and configuring CloudFront CDN with the files in S3 as origin, using RDS for your database tier and then going over the AWS SDK for PHP as a tool to interact with all of these cool services from within your PHP scripts. By the end of this tutorial, you will have gained the needed confidence from hands-on experience to start using cloud based infrastructure on future projects.',
            'room' => 'Acacia',
            'joindin' => 'http://joind.in/6343',
            'date' => '2012-06-29',
            'time' => '1545',
        ),
        '11' => array(
            'title' => 'It Was Like That When I Got Here: Steps Toward Modernizing a Legacy Codebase',
            'presenter' => 'Paul Jones',
            'description' => 'We\'ve all been there, dropped into a codebase that makes perfect sense to the current developers but might as well be Greek to you. Paul will help you make sense of things with some helpful tips for untangling the spaghetti and refactoring like a pro. He\'ll show you how to move it towards a more modern, modular architecture and keep it running the whole time.',
            'room' => 'Sycamore',
            'joindin' => 'http://joind.in/6700',
            'date' => '2012-06-30',
            'time' => '0900',
        ),
        '12' => array(
            'title' => 'SOLID - Not Just a State of Matter, It\'s Principles for OO Propriety',
            'presenter' => 'Chris Weldon',
            'description' => 'Principles abound our lives. Software and engineering is no exception. The more you develop software, the more patterns and principles you master. Yet, solutions remain difficult to maintain and developers are frequently frustrated by impediments they introduce and the waste generated to get around them. But why do we run into these roadblocks? It could be that you\'re not using the principles of object-oriented development to build better solutions. The SOLID principles are an important foundation for how to leverage OO languages to produce high value, low overhead, maintainable solutions. Whether you\'ve just starting to sling code or have been a veteran in the industry, the principles taught in this presentation are invaluable.',
            'room' => 'Sycamore',
            'joindin' => 'http://joind.in/6345',
            'date' => '2012-06-30',
            'time' => '1000',
        ),
        '13' => array(
            'title' => 'Padawan and Master - Mentoring Developers',
            'presenter' => 'Elizabeth Smith',
            'description' => 'One of the best ways to move yourself forward as a developer is to have mentors who can forward your skills, or to be a mentor for a newer developer. Mentoring isn\'t limited to just "hard" or technical skills, and a mentoring relationship can help in all aspects of any career - be it open source, a day job, or something else entirely. Learn some skills and tips from people who make mentoring an important aspect of their lives. From how to choose a mentor and what you should expect from a relationship as a padawan, to how to deal with the trials and successes of the person you are mentoring as they grow in their career.',
            'room' => 'Acacia',
            'joindin' => 'http://joind.in/6346',
            'date' => '2012-06-30',
            'time' => '1000',
        ),
        '14' => array(
            'title' => 'RESTful APIs and Self-Building Applications',
            'presenter' => 'Vance Lucas',
            'description' => 'What if your application had all of the information it needed from your REST API to build itself? We will take a look at some common REST API outputs and see what needs to be added to them to make them more RESTful, and then we will consume our new API in a live custom application to demonstrate how we might automate building parts of the UI from the API response alone.',
            'room' => 'Sycamore',
            'joindin' => 'http://joind.in/6347',
            'date' => '2012-06-30',
            'time' => '1100',
        ),
        '15' => array(
            'title' => 'Improve your tool chain for stress-free deployments',
            'presenter' => 'Omni Adams',
            'description' => 'When you deploy your software, do you find yourself doing it at odd hours in case something breaks? Do you have your whole team on hand to make sure everything went according to plan? If something bad happens, can you reverse the process before you get fired? Improving your tool chain can help make it easier to deploy your code, which can help keep your sanity... and your job. Easier deployments lead to more deployments which leads to a quicker time to market with less chance of bringing the site to its knees.',
            'room' => 'Acacia',
            'joindin' => 'http://joind.in/6348',
            'date' => '2012-06-30',
            'time' => '1100',
        ),
        '16' => array(
            'title' => 'Fast, Not Furious: Performance Tuning that Works',
            'presenter' => 'Davey Shafik',
            'description' => 'There\'s a saying "hardware is cheaper than developers", but this only holds true if you treat your hardware with the respect it deserves. Learn how to diagnose, confirm and fix bottlenecks in your application using new tools like XHProf and tried and true tools like xdebug. Also, we\'ll take an in-depth look at apc (advanced PHP cache) and memcache; even if you know and use memcache, this one can probably teach you a thing or two.',
            'room' => 'Sycamore',
            'joindin' => 'http://joind.in/6349',
            'date' => '2012-06-30',
            'time' => '1330',
        ),
        '17' => array(
            'title' => 'Devouring APIs with PHP and beanstalkd',
            'presenter' => 'John Syrinek',
            'description' => 'Aggregating data from third-party APIs is fairly basic ... until you have users. Today\'s users expect near-realtime data and lots of it. Anyone can consume API endpoints, but this 50 minute session will teach you how to take your web application to the next level with a simple approach to asynchronous web crawling that is fast, reliable, easy to debug, and scalable.',
            'room' => 'Acacia',
            'joindin' => 'http://joind.in/6350',
            'date' => '2012-06-30',
            'time' => '1330',
        ),
        '18' => array(
            'title' => 'Micro Framework and JavaScript Applications',
            'presenter' => 'Jeff Carouth',
            'description' => 'Small footprint libraries and so-called micro frameworks are a newer development in the PHP community. In this session we\'ll look at the MicroPHP Manifesto and go over building an application focused on the ideas presented by it. We\'ll look at a couple micro frameworks and other tools including Slim and Breeze as well as concerns with implementing your frontend with Backbone.js and other techniques. We\'ll also cover simple ways to organize your application and manage dependencies using Composer.',
            'room' => 'Sycamore',
            'joindin' => 'http://joind.in/6351',
            'date' => '2012-06-30',
            'time' => '1430',
        ),
        '19' => array(
            'title' => 'Intro to Lithium',
            'presenter' => 'Garrett Woodworth',
            'description' => 'Every framework claims to help you build the next killer app in less time and with less effort , but do they really help you do it your way? In this tactical tour-de-force, you\'ll learn how Lithium pulls together different tools, technologies, and paradigms to assist even the most complex and diabolical plans. By the end of the session, you\'ll know each step in the process required to get from zero to Instragram using Lithium.',
            'room' => 'Acacia',
            'joindin' => 'http://joind.in/6352',
            'date' => '2012-06-30',
            'time' => '1430',
        ),
        '20' => array(
            'title' => 'MongoDB and PHP',
            'presenter' => 'Derick Rethans',
            'description' => 'MongoDB is a scalable, high-performance, open source, document-oriented NoSQL database. It features document-oriented, JSON-based document storage and dynamic schemas providing simplicity, power and flexibility, combined with full indexes similar to what a traditional RDBMS user would expect. MongoDB also provides solid replication & high availability features as well as an auto-sharding system for transparent horizontal scalability. This talk introduces MongoDB for developers who aren\'t familiar with it with a detailed introduction of how to work with MongoDB from PHP. This talk will cover the basics from installing the PHP driver and connecting to mongod to creating, inserting, querying for, and updating documents. We will also briefly touch on aggregation, geospatial indexes, GridFS and running database commands.',
            'room' => 'Sycamore',
            'joindin' => 'http://joind.in/6353',
            'date' => '2012-06-30',
            'time' => '1530',
        ),
        '21' => array(
            'title' => 'Service-Oriented Architectures with ZeroMQ',
            'presenter' => 'Joël Perras',
            'description' => 'ZeroMQ has been getting quite a lot of attention, and with good reason. Branded as a "socket library that acts as a concurrency framework" that\'s faster than TCP and lets you build out your own topologies, it\'s been used to write broker-less message queues, webservers, chat servers, and hundreds of other applications that demand highly concurrent and asynchronous transport layers. But how can ZeroMQ help normal, every-day web developers create more robust and decoupled applications? We\'ll take a whirlwind tour through ZeroMQ, what it\'s capable of, and then create a simple, scalable and effective service-oriented architecture that will leave you wondering where ZeroMQ has been all your life.',
            'room' => 'Acacia',
            'joindin' => 'http://joind.in/6354',
            'date' => '2012-06-30',
            'time' => '1530',
        ),
        '22' => array(
            'title' => 'User Interface is more than Pixels',
            'presenter' => 'Keith Casey',
            'description' => 'Despite web applications becoming more and more ingrained in our day to day work and lives, most of the time we still interact with flat text on a screen. If we\'re really lucky, there are color visual cues mixed in. What if we could use our applications as easily as we use a phone? In this session, we\'ll explore integrating voice and text communications into our applications as a way of promoting Web Accessibility, interface flexibility, and getting away from our keyboards.',
            'room' => 'Sycamore',
            'joindin' => 'http://joind.in/6355',
            'date' => '2012-06-30',
            'time' => '1630',
        ),
        '23' => array(
            'title' => 'Infrastructure Debt',
            'presenter' => 'Chris Hartjes',
            'description' => 'You might have come across the term “technical debt”, used to describe the small mistakes that are made in your code base as the application grows and requirements change. You end up with a big tangled mess if you are not very careful about how you make those changes. If you’ve ever worked on an application where you were afraid to make changes for fear of breaking something, then you have run into technical debt. Technical debt can be dealt with via ruthless refactoring and wrapping your application in tests that poke and prod at the edge cases that your application deals with. But there is another type of debt you end up dealing with. One that is even more difficult to deal with and change. I call it infrastructure debt. Infrastructure debt is debt that you build up because you have not been paying attention to the process of creating the environments your application will exist in and have not been paying attention to the process of how your code gets from development into production. In my opinion, infrastructure debt is much more difficult to “pay off” than technical debt. Why? It is often very difficult for people to understand that it even exists. This talk will cover strategies for dealing with the scourge that is infrastructure debt.',
            'room' => 'Acacia',
            'joindin' => 'http://joind.in/6356',
            'date' => '2012-06-30',
            'time' => '1630',
        ),
    ),
    'schedule' => array(
        '2012-06-29' => array(
            '0800' => array(
                'end' => false,
                'type' => 'Registration',
                'talks' => array(),
                'room' => 'Sycamore',
            ),
            '0900' => array(
                'end' => false,
                'type' => 'Welcome',
                'talks' => array(),
                'room' => 'Sycamore',
            ),
            '0920' => array(
                'end' => '1010',
                'type' => 'Keynote',
                'talks' => array(1),
                'room' => 'Sycamore',
            ),
            '1030' => array(
                'end' => '1120',
                'type' => 'Session',
                'talks' => array(2,24),
                'room' => null,
            ),
            '1130' => array(
                'end' => '1220',
                'type' => 'Session',
                'talks' => array(3,4),
                'room' => null,
            ),
            '1220' => array(
                'end' => '1330',
                'type' => 'Lunch',
                'talks' => array(),
                'room' => 'Sycamore',
            ),
            '1345' => array(
                'end' => '1435',
                'type' => 'Session',
                'talks' => array(5,6),
                'room' => null,
            ),
            '1445' => array(
                'end' => '1535',
                'type' => 'Session',
                'talks' => array(7,8),
                'room' => null,
            ),
            '1545' => array(
                'end' => '1635',
                'type' => 'Session',
                'talks' => array(9,10),
                'room' => null,
            ),
            '1730' => array(
                'end' => '2030',
                'type' => 'After Party',
                'talks' => array(),
                'room' => 'Sycamore',
            ),
        ),
        '2012-06-30' => array(
            '0900' => array(
                'end' => '0950',
                'type' => 'Keynote',
                'talks' => array(11),
                'room' => 'Sycamore',
            ),
            '1000' => array(
                'end' => '1050',
                'type' => 'Session',
                'talks' => array(12,13),
                'room' => null,
            ),
            '1100' => array(
                'end' => '1150',
                'type' => 'Session',
                'talks' => array(14,15),
                'room' => null,
            ),
            '1200' => array(
                'end' => '1320',
                'type' => 'Lunch',
                'talks' => array(),
                'room' => 'Sycamore',
            ),
            '1330' => array(
                'end' => '1420',
                'type' => 'Session',
                'talks' => array(16,17),
                'room' => null,
            ),
            '1430' => array(
                'end' => '1520',
                'type' => 'Session',
                'talks' => array(18,19),
                'room' => null,
            ),
            '1530' => array(
                'end' => '1620',
                'type' => 'Session',
                'talks' => array(20,21),
                'room' => null,
            ),
            '1630' => array(
                'end' => '1720',
                'type' => 'Session',
                'talks' => array(22,23),
                'room' => null,
            ),
            '1730' => array(
                'end' => '1745',
                'type' => 'Closing Remarks',
                'talks' => array(),
                'room' => 'Sycamore',
            ),
            '1800' => array(
                'end' => '2100',
                'type' => 'After Party',
                'talks' => array(),
                'room' => 'Sycamore',
            ),
        ),
    ),
);